###
# USAGE: docker build -f Dockerfile-Infra-Cleaner -t infra-cleaner .
# RUN: docker run -it --network host --env-file .env_infra_cleaner  -v "$(pwd)/out:/srv" infra-cleaner
FROM alpine:3.15

RUN apk update --no-cache && \
    apk upgrade --no-cache && \
    apk add --no-cache --upgrade postgresql14 py3-pip

COPY requirements.txt /root
RUN pip3 install -r /root/requirements.txt
COPY src/verifier/central_verifier.py /root
WORKDIR /root/
CMD [ "python3", "/root/central_verifier.py" ]